In [33]:
import pandas as pd
from geopy.geocoders import GoogleV3
import json

In [11]:
# Read haded CSV into DataFrame
earthquakes = pd.read_csv('database.csv')

In [12]:
earthquakes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
Date                          23412 non-null object
Time                          23412 non-null object
Latitude                      23412 non-null float64
Longitude                     23412 non-null float64
Type                          23412 non-null object
Depth                         23412 non-null float64
Depth Error                   4461 non-null float64
Depth Seismic Stations        7097 non-null float64
Magnitude                     23412 non-null float64
Magnitude Type                23409 non-null object
Magnitude Error               327 non-null float64
Magnitude Seismic Stations    2564 non-null float64
Azimuthal Gap                 7299 non-null float64
Horizontal Distance           1604 non-null float64
Horizontal Error              1156 non-null float64
Root Mean Square              17352 non-null float64
ID                            23412 non-null object
Source                        23412 non-null object
Location Source               23412 non-null object
Magnitude Source              23412 non-null object
Status                        23412 non-null object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [13]:
earthquakes.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [35]:
geolocator = GoogleV3(api_key='AIzaSyDapkiVzfLpBSfmDELk7NIc5p0Anz90vOw')

In [125]:
def get_country(row):
    status_errors = []
    try:
        pos = str(row['Latitude']) + ', ' + str(row['Longitude'])
        locations = geolocator.reverse(pos, timeout = 10)
        for location in locations:
            for component in location.raw['address_components']:
                if 'country' in component['types']:
                    print(component['long_name'])
                    return component['long_name']
    except Exception as e:
        print('\033[93m' + str(pos) + ": " + str(e) + '\033[0m')
        status_errors.append(pos)

In [133]:
#earthquakes['country'] = 
earthquakes[19928:19939].apply(lambda row: get_country(row), axis = 1)

Chile
-54.027, -133.64: 'NoneType' object is not iterable
Chile
Argentina
Chile
Chile
Chile
Chile
Chile
Chile
Chile

19928        Chile
19929         None
19930        Chile
19931    Argentina
19932        Chile
19933        Chile
19934        Chile
19935        Chile
19936        Chile
19937        Chile
19938        Chile
dtype: object